CREATE TABLE `guestSessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`token` varchar(128) NOT NULL,
	`email` varchar(320) NOT NULL,
	`name` varchar(200),
	`organization` varchar(200),
	`country` varchar(100),
	`entityType` enum('regulator','public_operator','private_operator','consultant','other'),
	`currentPhaseIndex` int NOT NULL DEFAULT 0,
	`answers` json,
	`scores` json,
	`gaps` json,
	`actionPlan` json,
	`status` enum('in_progress','completed') NOT NULL DEFAULT 'in_progress',
	`benchmarkEmailSent` boolean NOT NULL DEFAULT false,
	`completedAt` timestamp,
	`expiresAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `guestSessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `guestSessions_token_unique` UNIQUE(`token`)
);
