/**
 * Seed script — NetDiscover v3
 * Phase 0 (context, not scored) + Phases 1–7 (4 scored questions + 1 barrier each)
 * Scale: 4 levels (1=Does not exist, 2=Initial, 3=Established, 4=Advanced)
 * Run: npx tsx server/seed.ts
 */
import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import { marketProviders, phases, questions } from "../drizzle/schema";
import dotenv from "dotenv";
dotenv.config();

const PHASES_DATA = [
  {
    slug: "phase0", orderIndex: 0,
    titleEs: "Contexto del Regulador",
    titleEn: "Regulator Context",
    titleFr: "Contexte du Régulateur",
    descriptionEs: "Perfil institucional, prioridades estratégicas y relación con el operador designado.",
    descriptionEn: "Institutional profile, strategic priorities and relationship with the designated operator.",
    descriptionFr: "Profil institutionnel, priorités stratégiques et relation avec l'opérateur désigné.",
    icon: "Building2", color: "#6B7280", scoringExcluded: true,
  },
  {
    slug: "phase1", orderIndex: 1,
    titleEs: "Diseño del Sistema de Medición",
    titleEn: "Measurement System Design",
    titleFr: "Conception du Système de Mesure",
    descriptionEs: "Metodología, panel de panelistas, plataforma tecnológica y capacidad técnica del equipo.",
    descriptionEn: "Methodology, panelist panel, technology platform and team technical capacity.",
    descriptionFr: "Méthodologie, panel de panélistes, plateforme technologique et capacité technique.",
    icon: "Settings2", color: "#0077C8", scoringExcluded: false,
  },
  {
    slug: "phase2", orderIndex: 2,
    titleEs: "Mapeo del Ecosistema",
    titleEn: "Ecosystem Mapping",
    titleFr: "Cartographie de l'Écosystème",
    descriptionEs: "Inventario de actores, documentación de la red postal, volúmenes y topología.",
    descriptionEn: "Actor inventory, postal network documentation, volumes and topology.",
    descriptionFr: "Inventaire des acteurs, documentation du réseau postal, volumes et topologie.",
    icon: "Map", color: "#7C3AED", scoringExcluded: false,
  },
  {
    slug: "phase3", orderIndex: 3,
    titleEs: "Establecimiento de SLAs",
    titleEn: "SLA Establishment",
    titleFr: "Établissement des SLA",
    descriptionEs: "Línea base, definición de SLAs, formalización legal y revisión periódica.",
    descriptionEn: "Baseline, SLA definition, legal formalization and periodic review.",
    descriptionFr: "Référence de base, définition des SLA, formalisation juridique et révision périodique.",
    icon: "FileCheck", color: "#059669", scoringExcluded: false,
  },
  {
    slug: "phase4", orderIndex: 4,
    titleEs: "Diagnóstico de Red",
    titleEn: "Network Diagnosis",
    titleFr: "Diagnostic du Réseau",
    descriptionEs: "Identificación de nodos críticos, tecnología RFID, diagnóstico automático y acceso del operador.",
    descriptionEn: "Critical node identification, RFID technology, automatic diagnosis and operator access.",
    descriptionFr: "Identification des nœuds critiques, technologie RFID, diagnostic automatique et accès opérateur.",
    icon: "Network", color: "#D97706", scoringExcluded: false,
  },
  {
    slug: "phase5", orderIndex: 5,
    titleEs: "Medición Continua",
    titleEn: "Continuous Measurement",
    titleFr: "Mesure Continue",
    descriptionEs: "Operación permanente, reportería estructurada, transparencia y alertas automáticas.",
    descriptionEn: "Permanent operation, structured reporting, transparency and automatic alerts.",
    descriptionFr: "Fonctionnement permanent, rapports structurés, transparence et alertes automatiques.",
    icon: "Activity", color: "#DC2626", scoringExcluded: false,
  },
  {
    slug: "phase6", orderIndex: 6,
    titleEs: "Planes de Mejora",
    titleEn: "Improvement Plans",
    titleFr: "Plans d'Amélioration",
    descriptionEs: "Análisis de causa raíz, planes formales, capacidad sancionadora y verificación de impacto.",
    descriptionEn: "Root cause analysis, formal plans, sanctioning capacity and impact verification.",
    descriptionFr: "Analyse des causes profondes, plans formels, capacité de sanction et vérification d'impact.",
    icon: "TrendingUp", color: "#0891B2", scoringExcluded: false,
  },
  {
    slug: "phase7", orderIndex: 7,
    titleEs: "Madurez y Mejora Continua",
    titleEn: "Maturity & Continuous Improvement",
    titleFr: "Maturité et Amélioration Continue",
    descriptionEs: "Revisión de SLAs, nuevos servicios, benchmarking internacional y satisfacción del usuario.",
    descriptionEn: "SLA review, new services, international benchmarking and user satisfaction.",
    descriptionFr: "Révision des SLA, nouveaux services, benchmarking international et satisfaction des utilisateurs.",
    icon: "Award", color: "#7C3AED", scoringExcluded: false,
  },
];

type BarrierOption = { value: string; labelEs: string; labelEn: string; labelFr: string };
type QuestionRaw = {
  ps: string; oi: number; slug: string; type: "scale" | "barrier"; w: string;
  es: string; en: string; fr: string; hes: string; hen: string; hfr: string;
  options?: BarrierOption[];
};

const Q: QuestionRaw[] = [
  // ── Phase 0: Regulator Context (not scored) ──────────────────────────────
  { ps:"phase0",oi:1,slug:"p0q1",type:"scale",w:"0.00",
    es:"¿En qué medida la mejora de la calidad del servicio postal es una prioridad estratégica declarada de su institución?",
    en:"To what extent is improving postal service quality a declared strategic priority of your institution?",
    fr:"Dans quelle mesure l'amélioration de la qualité du service postal est-elle une priorité stratégique déclarée de votre institution?",
    hes:"1=No es prioridad / 2=Prioridad secundaria / 3=Prioridad declarada sin recursos asignados / 4=Prioridad estratégica con recursos y plan",
    hen:"1=Not a priority / 2=Secondary priority / 3=Declared priority without assigned resources / 4=Strategic priority with resources and plan",
    hfr:"1=Pas une priorité / 2=Priorité secondaire / 3=Priorité déclarée sans ressources / 4=Priorité stratégique avec ressources et plan" },
  { ps:"phase0",oi:2,slug:"p0q2",type:"scale",w:"0.00",
    es:"¿Cuál describe mejor la relación entre el regulador y el operador designado en materia de calidad?",
    en:"Which best describes the relationship between the regulator and the designated operator on quality matters?",
    fr:"Laquelle décrit le mieux la relation entre le régulateur et l'opérateur désigné en matière de qualité?",
    hes:"1=Sin relación activa / 2=Relación formal sin colaboración / 3=Diálogo activo sin herramientas compartidas / 4=Colaboración estructurada con datos y objetivos compartidos",
    hen:"1=No active relationship / 2=Formal relationship without collaboration / 3=Active dialogue without shared tools / 4=Structured collaboration with shared data and objectives",
    hfr:"1=Pas de relation active / 2=Relation formelle sans collaboration / 3=Dialogue actif sans outils partagés / 4=Collaboration structurée avec données et objectifs partagés" },
  { ps:"phase0",oi:3,slug:"p0q3",type:"scale",w:"0.00",
    es:"¿En qué medida el operador designado ha expresado necesidad de apoyo técnico para mejorar su calidad de servicio?",
    en:"To what extent has the designated operator expressed a need for technical support to improve its service quality?",
    fr:"Dans quelle mesure l'opérateur désigné a-t-il exprimé un besoin de soutien technique pour améliorer sa qualité de service?",
    hes:"1=Nunca lo ha expresado / 2=Lo ha mencionado informalmente / 3=Lo ha solicitado formalmente sin proyecto definido / 4=Existe un programa activo de soporte técnico al DO",
    hen:"1=Never expressed it / 2=Mentioned it informally / 3=Formally requested without defined project / 4=Active technical support programme for the DO exists",
    hfr:"1=Ne l'a jamais exprimé / 2=L'a mentionné informellement / 3=L'a demandé formellement sans projet défini / 4=Programme actif de soutien technique à l'OD" },
  { ps:"phase0",oi:4,slug:"p0q4",type:"scale",w:"0.00",
    es:"¿Con qué nivel de autoridad legal cuenta el regulador para exigir mediciones independientes y sancionar incumplimientos?",
    en:"What level of legal authority does the regulator have to require independent measurements and sanction non-compliance?",
    fr:"Quel niveau d'autorité légale le régulateur possède-t-il pour exiger des mesures indépendantes et sanctionner les manquements?",
    hes:"1=Sin autoridad legal específica / 2=Solo recomendaciones / 3=Puede medir y publicar pero sin régimen sancionador / 4=Autoridad completa (medir, exigir, sancionar, publicar)",
    hen:"1=No specific legal authority / 2=Recommendations only / 3=Can measure and publish but no sanctioning regime / 4=Full authority (measure, require, sanction, publish)",
    hfr:"1=Pas d'autorité légale spécifique / 2=Recommandations seulement / 3=Peut mesurer et publier sans régime de sanction / 4=Autorité complète (mesurer, exiger, sanctionner, publier)" },
  { ps:"phase0",oi:5,slug:"p0q5",type:"barrier",w:"0.00",
    es:"¿Cuál es el principal obstáculo para avanzar en calidad postal en su país?",
    en:"What is the main obstacle to advancing postal quality in your country?",
    fr:"Quel est le principal obstacle à l'avancement de la qualité postale dans votre pays?",
    hes:"Seleccione el obstáculo más relevante para su contexto.",
    hen:"Select the most relevant obstacle for your context.",
    hfr:"Sélectionnez l'obstacle le plus pertinent pour votre contexte.",
    options:[
      {value:"budget",labelEs:"Falta de presupuesto",labelEn:"Lack of budget",labelFr:"Manque de budget"},
      {value:"legal",labelEs:"Falta de autoridad legal",labelEn:"Lack of legal authority",labelFr:"Manque d'autorité légale"},
      {value:"operator_resistance",labelEs:"Resistencia del operador",labelEn:"Operator resistance",labelFr:"Résistance de l'opérateur"},
      {value:"technical_capacity",labelEs:"Falta de capacidad técnica",labelEn:"Lack of technical capacity",labelFr:"Manque de capacité technique"},
      {value:"political_will",labelEs:"Falta de voluntad política",labelEn:"Lack of political will",labelFr:"Manque de volonté politique"},
      {value:"not_priority",labelEs:"No es prioridad del gobierno",labelEn:"Not a government priority",labelFr:"Pas une priorité gouvernementale"},
    ]},

  // ── Phase 1: Measurement System Design ───────────────────────────────────
  { ps:"phase1",oi:1,slug:"p1q1",type:"scale",w:"2.00",
    es:"¿En qué estado se encuentra la metodología de medición de calidad postal del país?",
    en:"What is the current state of the country's postal quality measurement methodology?",
    fr:"Quel est l'état actuel de la méthodologie de mesure de la qualité postale du pays?",
    hes:"1=No existe metodología / 2=Existe un diseño conceptual o borrador pero no se ha implementado / 3=Metodología implementada pero sin alineación formal con estándares internacionales / 4=Metodología operativa, alineada con UPU S58/S59 o EN 13850, con validación estadística",
    hen:"1=No methodology exists / 2=Conceptual design or draft exists but not implemented / 3=Methodology implemented but not formally aligned with international standards / 4=Operational methodology, aligned with UPU S58/S59 or EN 13850, with statistical validation",
    hfr:"1=Pas de méthodologie / 2=Conception conceptuelle ou brouillon non mis en œuvre / 3=Méthodologie mise en œuvre sans alignement formel / 4=Méthodologie opérationnelle, alignée UPU S58/S59 ou EN 13850, avec validation statistique" },
  { ps:"phase1",oi:2,slug:"p1q2",type:"scale",w:"2.00",
    es:"¿Qué nivel de implementación tiene el panel de medición con panelistas independientes?",
    en:"What level of implementation does the measurement panel with independent panelists have?",
    fr:"Quel niveau de mise en œuvre le panel de mesure avec des panélistes indépendants a-t-il?",
    hes:"1=No existe panel / 2=Se ha diseñado o pilotado pero no está operativo / 3=Panel operativo pero con cobertura geográfica parcial o volumen insuficiente / 4=Panel operativo con cobertura representativa, volumen estadísticamente válido y auditoría periódica",
    hen:"1=No panel exists / 2=Designed or piloted but not operational / 3=Operational panel but with partial geographic coverage or insufficient volume / 4=Operational panel with representative coverage, statistically valid volume and periodic audit",
    hfr:"1=Pas de panel / 2=Conçu ou piloté mais non opérationnel / 3=Panel opérationnel avec couverture partielle ou volume insuffisant / 4=Panel opérationnel avec couverture représentative, volume statistiquement valide et audit périodique" },
  { ps:"phase1",oi:3,slug:"p1q3",type:"scale",w:"1.50",
    es:"¿Qué nivel de desarrollo tiene la plataforma tecnológica para gestionar los datos de medición?",
    en:"What level of development does the technology platform for managing measurement data have?",
    fr:"Quel niveau de développement la plateforme technologique pour gérer les données de mesure a-t-elle?",
    hes:"1=No existe plataforma (hojas de cálculo o métodos manuales) / 2=Herramienta básica sin automatización ni dashboards / 3=Plataforma con ingesta de datos y dashboards pero sin alertas ni reportería automatizada / 4=Plataforma integrada con ingesta automática, dashboards, alertas, reportería y gestión de SLAs",
    hen:"1=No platform (spreadsheets or manual methods) / 2=Basic tool without automation or dashboards / 3=Platform with data ingestion and dashboards but no alerts or automated reporting / 4=Integrated platform with automatic ingestion, dashboards, alerts, reporting and SLA management",
    hfr:"1=Pas de plateforme (tableurs ou méthodes manuelles) / 2=Outil basique sans automatisation ni tableaux de bord / 3=Plateforme avec ingestion de données et tableaux de bord sans alertes / 4=Plateforme intégrée avec ingestion automatique, tableaux de bord, alertes, rapports et gestion des SLA" },
  { ps:"phase1",oi:4,slug:"p1q4",type:"scale",w:"1.50",
    es:"¿Qué capacidad técnica tiene el equipo del regulador para operar e interpretar el sistema de medición?",
    en:"What technical capacity does the regulator's team have to operate and interpret the measurement system?",
    fr:"Quelle capacité technique l'équipe du régulateur a-t-elle pour opérer et interpréter le système de mesure?",
    hes:"1=No hay personal asignado a calidad postal / 2=Hay personal asignado pero sin formación específica / 3=Equipo formado que opera el sistema pero depende de soporte externo / 4=Equipo especializado autónomo con capacidad de operación, análisis y evolución del sistema",
    hen:"1=No staff assigned to postal quality / 2=Staff assigned but without specific training / 3=Trained team operating the system but dependent on external support / 4=Autonomous specialized team with capacity to operate, analyse and evolve the system",
    hfr:"1=Pas de personnel affecté à la qualité postale / 2=Personnel affecté sans formation spécifique / 3=Équipe formée opérant le système mais dépendante du soutien externe / 4=Équipe spécialisée autonome capable d'opérer, analyser et faire évoluer le système" },
  { ps:"phase1",oi:5,slug:"p1q5",type:"barrier",w:"0.00",
    es:"¿Cuál es el principal obstáculo para desarrollar su sistema de medición?",
    en:"What is the main obstacle to developing your measurement system?",
    fr:"Quel est le principal obstacle au développement de votre système de mesure?",
    hes:"Seleccione el obstáculo más relevante.",hen:"Select the most relevant obstacle.",hfr:"Sélectionnez l'obstacle le plus pertinent.",
    options:[
      {value:"no_budget",labelEs:"No hay presupuesto para medición",labelEn:"No budget for measurement",labelFr:"Pas de budget pour la mesure"},
      {value:"no_methodology",labelEs:"No hay metodología definida",labelEn:"No defined methodology",labelFr:"Pas de méthodologie définie"},
      {value:"no_staff",labelEs:"No se encuentra personal técnico cualificado",labelEn:"Cannot find qualified technical staff",labelFr:"Impossible de trouver du personnel technique qualifié"},
      {value:"operator_no_cooperate",labelEs:"El operador no colabora con la instalación de equipamiento",labelEn:"Operator does not cooperate with equipment installation",labelFr:"L'opérateur ne coopère pas à l'installation des équipements"},
      {value:"no_local_tech",labelEs:"No hay tecnología disponible localmente",labelEn:"No technology available locally",labelFr:"Pas de technologie disponible localement"},
      {value:"already_works",labelEs:"Ya tenemos un sistema que funciona bien",labelEn:"We already have a well-functioning system",labelFr:"Nous avons déjà un système qui fonctionne bien"},
    ]},

  // ── Phase 2: Ecosystem Mapping ────────────────────────────────────────────
  { ps:"phase2",oi:1,slug:"p2q1",type:"scale",w:"2.00",
    es:"¿En qué estado se encuentra el inventario de actores del ecosistema postal (operadores, carriers, subcontratistas)?",
    en:"What is the state of the postal ecosystem actor inventory (operators, carriers, subcontractors)?",
    fr:"Quel est l'état de l'inventaire des acteurs de l'écosystème postal (opérateurs, transporteurs, sous-traitants)?",
    hes:"1=No existe inventario / 2=Inventario parcial o desactualizado / 3=Inventario completo pero sin detalle de tramos, frecuencias y relaciones contractuales / 4=Inventario completo, actualizado, con detalle de tramos, carriers y relaciones contractuales",
    hen:"1=No inventory exists / 2=Partial or outdated inventory / 3=Complete inventory but without detail on segments, frequencies and contractual relationships / 4=Complete, updated inventory with detail on segments, carriers and contractual relationships",
    hfr:"1=Pas d'inventaire / 2=Inventaire partiel ou obsolète / 3=Inventaire complet sans détail des segments, fréquences et relations contractuelles / 4=Inventaire complet et à jour avec détail des segments, transporteurs et relations contractuelles" },
  { ps:"phase2",oi:2,slug:"p2q2",type:"scale",w:"1.50",
    es:"¿En qué medida está documentada la estructura física de la red postal (nodos, rutas, frecuencias de transporte)?",
    en:"To what extent is the physical structure of the postal network documented (nodes, routes, transport frequencies)?",
    fr:"Dans quelle mesure la structure physique du réseau postal est-elle documentée (nœuds, itinéraires, fréquences de transport)?",
    hes:"1=No documentada / 2=Documentación parcial basada en información del operador sin verificar / 3=Documentación completa pero sin georeferenciación ni actualización periódica / 4=Red completamente documentada, georeferenciada y actualizada periódicamente",
    hen:"1=Not documented / 2=Partial documentation based on unverified operator information / 3=Complete documentation but without georeferencing or periodic updates / 4=Fully documented, georeferenced and periodically updated network",
    hfr:"1=Non documentée / 2=Documentation partielle basée sur des informations non vérifiées / 3=Documentation complète sans géoréférencement ni mises à jour périodiques / 4=Réseau entièrement documenté, géoréférencé et mis à jour périodiquement" },
  { ps:"phase2",oi:3,slug:"p2q3",type:"scale",w:"1.50",
    es:"¿Se conocen los volúmenes de correo por tipo de servicio y distribución geográfica?",
    en:"Are mail volumes known by service type and geographic distribution?",
    fr:"Les volumes de courrier sont-ils connus par type de service et distribution géographique?",
    hes:"1=No se conocen volúmenes / 2=Se conocen volúmenes totales sin desagregación / 3=Volúmenes desagregados por servicio pero sin distribución geográfica / 4=Volúmenes completos por servicio, zona geográfica y período, con datos verificados",
    hen:"1=Volumes not known / 2=Total volumes known without disaggregation / 3=Volumes disaggregated by service but without geographic distribution / 4=Complete volumes by service, geographic area and period, with verified data",
    hfr:"1=Volumes inconnus / 2=Volumes totaux connus sans désagrégation / 3=Volumes désagrégés par service sans distribution géographique / 4=Volumes complets par service, zone géographique et période, avec données vérifiées" },
  { ps:"phase2",oi:4,slug:"p2q4",type:"scale",w:"2.00",
    es:"¿Existe una topología postal con zonas de medición y pares origen-destino definidos?",
    en:"Is there a postal topology with measurement zones and defined origin-destination pairs?",
    fr:"Existe-t-il une topologie postale avec des zones de mesure et des paires origine-destination définies?",
    hes:"1=No existe topología / 2=Existe una división administrativa no adaptada a medición postal / 3=Topología definida con pares O-D pero sin validación con datos reales de volúmenes / 4=Topología aprobada formalmente, con pares O-D representativos validados con datos de volúmenes",
    hen:"1=No topology exists / 2=Administrative division not adapted to postal measurement / 3=Topology defined with O-D pairs but not validated with real volume data / 4=Formally approved topology with representative O-D pairs validated with volume data",
    hfr:"1=Pas de topologie / 2=Division administrative non adaptée à la mesure postale / 3=Topologie définie avec paires O-D sans validation avec données de volumes réels / 4=Topologie formellement approuvée avec paires O-D représentatives validées avec données de volumes" },
  { ps:"phase2",oi:5,slug:"p2q5",type:"barrier",w:"0.00",
    es:"¿Cuál es el principal obstáculo para completar el mapeo de su ecosistema postal?",
    en:"What is the main obstacle to completing the mapping of your postal ecosystem?",
    fr:"Quel est le principal obstacle à la cartographie complète de votre écosystème postal?",
    hes:"Seleccione el obstáculo más relevante.",hen:"Select the most relevant obstacle.",hfr:"Sélectionnez l'obstacle le plus pertinent.",
    options:[
      {value:"operator_no_share",labelEs:"El operador no comparte información sobre su red",labelEn:"Operator does not share network information",labelFr:"L'opérateur ne partage pas les informations sur son réseau"},
      {value:"no_resources",labelEs:"No hay recursos para realizar el levantamiento",labelEn:"No resources to conduct the survey",labelFr:"Pas de ressources pour réaliser le relevé"},
      {value:"network_changes",labelEs:"La red cambia frecuentemente y es difícil mantenerla actualizada",labelEn:"The network changes frequently and is difficult to keep updated",labelFr:"Le réseau change fréquemment et est difficile à maintenir à jour"},
      {value:"no_gis",labelEs:"No se dispone de herramientas GIS o de mapeo",labelEn:"No GIS or mapping tools available",labelFr:"Pas d'outils SIG ou de cartographie disponibles"},
      {value:"no_legal_obligation",labelEs:"No existe obligación legal de que el operador comparta estos datos",labelEn:"No legal obligation for the operator to share this data",labelFr:"Pas d'obligation légale pour l'opérateur de partager ces données"},
      {value:"already_complete",labelEs:"El mapeo ya está completo",labelEn:"The mapping is already complete",labelFr:"La cartographie est déjà complète"},
    ]},

  // ── Phase 3: SLA Establishment ────────────────────────────────────────────
  { ps:"phase3",oi:1,slug:"p3q1",type:"scale",w:"2.00",
    es:"¿Se ha realizado un período de medición inicial (línea base) para conocer la realidad del servicio antes de fijar objetivos?",
    en:"Has an initial measurement period (baseline) been conducted to understand service reality before setting objectives?",
    fr:"Une période de mesure initiale (référence de base) a-t-elle été réalisée pour connaître la réalité du service avant de fixer des objectifs?",
    hes:"1=Nunca se ha medido / 2=Se han hecho mediciones puntuales sin período de línea base estructurado / 3=Se realizó una línea base pero con cobertura o período insuficiente / 4=Línea base completa con período ≥3 meses, cobertura representativa y análisis estadístico",
    hen:"1=Never measured / 2=Spot measurements done without structured baseline period / 3=Baseline conducted but with insufficient coverage or period / 4=Complete baseline with period ≥3 months, representative coverage and statistical analysis",
    hfr:"1=Jamais mesuré / 2=Mesures ponctuelles sans période de référence structurée / 3=Référence réalisée mais avec couverture ou période insuffisante / 4=Référence complète avec période ≥3 mois, couverture représentative et analyse statistique" },
  { ps:"phase3",oi:2,slug:"p3q2",type:"scale",w:"2.00",
    es:"¿Qué nivel de formalización tienen los SLAs de calidad postal?",
    en:"What level of formalization do postal quality SLAs have?",
    fr:"Quel niveau de formalisation les SLA de qualité postale ont-ils?",
    hes:"1=No existen SLAs / 2=Existen objetivos internos del operador pero no vinculantes / 3=SLAs definidos formalmente pero sin consecuencias por incumplimiento / 4=SLAs vinculantes con instrumento legal, diferenciados por servicio y zona, con régimen de consecuencias",
    hen:"1=No SLAs exist / 2=Internal operator objectives exist but not binding / 3=Formally defined SLAs but without consequences for non-compliance / 4=Binding SLAs with legal instrument, differentiated by service and area, with consequences regime",
    hfr:"1=Pas de SLA / 2=Objectifs internes de l'opérateur mais non contraignants / 3=SLA formellement définis sans conséquences pour non-conformité / 4=SLA contraignants avec instrument légal, différenciés par service et zone, avec régime de conséquences" },
  { ps:"phase3",oi:3,slug:"p3q3",type:"scale",w:"1.50",
    es:"¿Se han establecido SLAs específicos por segmento para carriers subcontratados?",
    en:"Have specific segment SLAs been established for subcontracted carriers?",
    fr:"Des SLA spécifiques par segment ont-ils été établis pour les transporteurs sous-traités?",
    hes:"1=No existen SLAs con carriers / 2=Se conocen los carriers pero no hay SLAs por tramo / 3=Existen acuerdos con algunos carriers pero sin medición sistemática por tramo / 4=SLAs por tramo para todos los carriers, con medición en puntos de handover y atribución de responsabilidades",
    hen:"1=No SLAs with carriers / 2=Carriers known but no segment SLAs / 3=Agreements with some carriers but no systematic segment measurement / 4=Segment SLAs for all carriers, with measurement at handover points and responsibility attribution",
    hfr:"1=Pas de SLA avec les transporteurs / 2=Transporteurs connus mais pas de SLA par segment / 3=Accords avec certains transporteurs sans mesure systématique par segment / 4=SLA par segment pour tous les transporteurs, avec mesure aux points de transfert et attribution des responsabilités" },
  { ps:"phase3",oi:4,slug:"p3q4",type:"scale",w:"1.50",
    es:"¿Con qué frecuencia se revisan los SLAs basándose en datos acumulados?",
    en:"How frequently are SLAs reviewed based on accumulated data?",
    fr:"À quelle fréquence les SLA sont-ils révisés sur la base des données accumulées?",
    hes:"1=Nunca se han revisado / 2=Se han revisado de forma puntual sin periodicidad definida / 3=Revisión periódica pero sin proceso formal ni consulta a stakeholders / 4=Ciclo formal de revisión (anual o bianual) con datos acumulados, consulta a stakeholders y ajuste documentado",
    hen:"1=Never reviewed / 2=Reviewed sporadically without defined periodicity / 3=Periodic review but without formal process or stakeholder consultation / 4=Formal review cycle (annual or biennial) with accumulated data, stakeholder consultation and documented adjustment",
    hfr:"1=Jamais révisés / 2=Révisés ponctuellement sans périodicité définie / 3=Révision périodique sans processus formel ni consultation des parties prenantes / 4=Cycle formel de révision (annuel ou biennal) avec données accumulées, consultation et ajustement documenté" },
  { ps:"phase3",oi:5,slug:"p3q5",type:"barrier",w:"0.00",
    es:"¿Cuál es el principal obstáculo para establecer o mejorar sus SLAs?",
    en:"What is the main obstacle to establishing or improving your SLAs?",
    fr:"Quel est le principal obstacle à l'établissement ou à l'amélioration de vos SLA?",
    hes:"Seleccione el obstáculo más relevante.",hen:"Select the most relevant obstacle.",hfr:"Sélectionnez l'obstacle le plus pertinent.",
    options:[
      {value:"no_baseline",labelEs:"No hay datos de línea base para fundamentar los objetivos",labelEn:"No baseline data to support objectives",labelFr:"Pas de données de référence pour fonder les objectifs"},
      {value:"no_political_will",labelEs:"Falta de voluntad política para imponer SLAs vinculantes",labelEn:"Lack of political will to impose binding SLAs",labelFr:"Manque de volonté politique pour imposer des SLA contraignants"},
      {value:"operator_resistance",labelEs:"El operador se resiste a aceptar SLAs con consecuencias",labelEn:"Operator resists accepting SLAs with consequences",labelFr:"L'opérateur résiste à l'acceptation de SLA avec conséquences"},
      {value:"no_legal_framework",labelEs:"No existe marco legal para formalizar los SLAs",labelEn:"No legal framework to formalize SLAs",labelFr:"Pas de cadre juridique pour formaliser les SLA"},
      {value:"no_experience",labelEs:"Falta experiencia en diseño de SLAs postales",labelEn:"Lack of experience in postal SLA design",labelFr:"Manque d'expérience dans la conception de SLA postaux"},
      {value:"already_established",labelEs:"Los SLAs ya están establecidos y funcionan",labelEn:"SLAs are already established and working",labelFr:"Les SLA sont déjà établis et fonctionnent"},
    ]},

  // ── Phase 4: Network Diagnosis ────────────────────────────────────────────
  { ps:"phase4",oi:1,slug:"p4q1",type:"scale",w:"2.00",
    es:"¿Se han identificado los nodos críticos de la red postal donde se producen los mayores retrasos?",
    en:"Have the critical nodes of the postal network where the greatest delays occur been identified?",
    fr:"Les nœuds critiques du réseau postal où se produisent les plus grands retards ont-ils été identifiés?",
    hes:"1=No se conocen los nodos de la red / 2=Se conocen los nodos principales pero no dónde se producen los retrasos / 3=Se han identificado nodos problemáticos por observación o quejas pero sin datos de medición / 4=Nodos críticos identificados con datos de medición que muestran tiempos por segmento",
    hen:"1=Network nodes not known / 2=Main nodes known but not where delays occur / 3=Problematic nodes identified by observation or complaints but without measurement data / 4=Critical nodes identified with measurement data showing segment times",
    hfr:"1=Nœuds du réseau inconnus / 2=Nœuds principaux connus mais pas où se produisent les retards / 3=Nœuds problématiques identifiés par observation ou plaintes sans données de mesure / 4=Nœuds critiques identifiés avec données de mesure montrant les temps par segment" },
  { ps:"phase4",oi:2,slug:"p4q2",type:"scale",w:"2.00",
    es:"¿Qué nivel de implementación tiene la tecnología de captura (RFID, código de barras) en los nodos de la red?",
    en:"What level of implementation does capture technology (RFID, barcodes) have at network nodes?",
    fr:"Quel niveau de mise en œuvre la technologie de capture (RFID, codes-barres) a-t-elle aux nœuds du réseau?",
    hes:"1=No existe tecnología de captura / 2=Se ha diseñado o pilotado en algunos nodos pero no está operativa / 3=Tecnología instalada en nodos principales pero sin cobertura completa / 4=Red de captura operativa en todos los nodos críticos, integrada con la plataforma y con mantenimiento establecido",
    hen:"1=No capture technology exists / 2=Designed or piloted at some nodes but not operational / 3=Technology installed at main nodes but without full network coverage / 4=Operational capture network at all critical nodes, integrated with platform and with established maintenance",
    hfr:"1=Pas de technologie de capture / 2=Conçue ou pilotée sur certains nœuds mais non opérationnelle / 3=Technologie installée sur les nœuds principaux sans couverture complète / 4=Réseau de capture opérationnel sur tous les nœuds critiques, intégré à la plateforme avec maintenance établie" },
  { ps:"phase4",oi:3,slug:"p4q3",type:"scale",w:"1.50",
    es:"¿Puede el sistema descomponer el tiempo total de tránsito en segmentos y generar diagnósticos automáticos por nodo?",
    en:"Can the system decompose total transit time into segments and generate automatic diagnostics by node?",
    fr:"Le système peut-il décomposer le temps de transit total en segments et générer des diagnostics automatiques par nœud?",
    hes:"1=No es posible descomponer tiempos / 2=Se pueden estimar tiempos por segmento de forma manual / 3=La plataforma calcula tiempos por segmento pero sin dashboards ni alertas / 4=Diagnóstico automático con dashboards por nodo, análisis de cuellos de botella y alertas por degradación",
    hen:"1=Cannot decompose times / 2=Segment times can be estimated manually / 3=Platform calculates segment times but without dashboards or alerts / 4=Automatic diagnosis with per-node dashboards, bottleneck analysis and degradation alerts",
    hfr:"1=Impossible de décomposer les temps / 2=Les temps par segment peuvent être estimés manuellement / 3=La plateforme calcule les temps par segment sans tableaux de bord ni alertes / 4=Diagnostic automatique avec tableaux de bord par nœud, analyse des goulots d'étranglement et alertes de dégradation" },
  { ps:"phase4",oi:4,slug:"p4q4",type:"scale",w:"1.50",
    es:"¿El operador designado tiene acceso a los datos de diagnóstico de su propia red para mejorar sus operaciones?",
    en:"Does the designated operator have access to diagnostic data of its own network to improve its operations?",
    fr:"L'opérateur désigné a-t-il accès aux données de diagnostic de son propre réseau pour améliorer ses opérations?",
    hes:"1=El operador no tiene acceso a datos de diagnóstico / 2=El operador recibe informes puntuales pero sin acceso directo / 3=El operador tiene acceso a dashboards básicos de su rendimiento / 4=El operador tiene acceso completo a datos de diagnóstico con dashboards propios para su planificación operativa",
    hen:"1=Operator has no access to diagnostic data / 2=Operator receives spot reports but no direct access / 3=Operator has access to basic performance dashboards / 4=Operator has full access to diagnostic data with own dashboards for operational planning",
    hfr:"1=L'opérateur n'a pas accès aux données de diagnostic / 2=L'opérateur reçoit des rapports ponctuels sans accès direct / 3=L'opérateur a accès à des tableaux de bord de performance de base / 4=L'opérateur a un accès complet aux données de diagnostic avec ses propres tableaux de bord" },
  { ps:"phase4",oi:5,slug:"p4q5",type:"barrier",w:"0.00",
    es:"¿Cuál es el principal obstáculo para diagnosticar su red postal?",
    en:"What is the main obstacle to diagnosing your postal network?",
    fr:"Quel est le principal obstacle au diagnostic de votre réseau postal?",
    hes:"Seleccione el obstáculo más relevante.",hen:"Select the most relevant obstacle.",hfr:"Sélectionnez l'obstacle le plus pertinent.",
    options:[
      {value:"no_budget_rfid",labelEs:"No hay presupuesto para equipamiento RFID",labelEn:"No budget for RFID equipment",labelFr:"Pas de budget pour les équipements RFID"},
      {value:"operator_no_install",labelEs:"El operador no permite instalar equipamiento en sus instalaciones",labelEn:"Operator does not allow equipment installation in its facilities",labelFr:"L'opérateur ne permet pas l'installation d'équipements dans ses installations"},
      {value:"no_infrastructure",labelEs:"Las instalaciones no tienen la infraestructura necesaria",labelEn:"Facilities lack the necessary infrastructure",labelFr:"Les installations manquent de l'infrastructure nécessaire"},
      {value:"no_technical_staff",labelEs:"No hay personal técnico para instalar y mantener los equipos",labelEn:"No technical staff to install and maintain equipment",labelFr:"Pas de personnel technique pour installer et maintenir les équipements"},
      {value:"no_rfid_supplier",labelEs:"No se dispone de proveedor de equipamiento RFID",labelEn:"No RFID equipment supplier available",labelFr:"Pas de fournisseur d'équipements RFID disponible"},
      {value:"already_diagnosed",labelEs:"La red ya está diagnosticada",labelEn:"The network is already diagnosed",labelFr:"Le réseau est déjà diagnostiqué"},
    ]},

  // ── Phase 5: Continuous Measurement ──────────────────────────────────────
  { ps:"phase5",oi:1,slug:"p5q1",type:"scale",w:"2.00",
    es:"¿El sistema de medición opera de forma continua y permanente o solo en campañas puntuales?",
    en:"Does the measurement system operate continuously and permanently or only in specific campaigns?",
    fr:"Le système de mesure fonctionne-t-il de manière continue et permanente ou seulement lors de campagnes ponctuelles?",
    hes:"1=No hay medición activa / 2=Se hacen campañas puntuales (una o dos veces al año) / 3=Medición continua pero con interrupciones frecuentes o períodos sin datos / 4=Medición permanente con operación estable, control de calidad de datos y sin interrupciones significativas",
    hen:"1=No active measurement / 2=Spot campaigns conducted (once or twice a year) / 3=Continuous measurement but with frequent interruptions or periods without data / 4=Permanent measurement with stable operation, data quality control and no significant interruptions",
    hfr:"1=Pas de mesure active / 2=Campagnes ponctuelles (une ou deux fois par an) / 3=Mesure continue avec interruptions fréquentes ou périodes sans données / 4=Mesure permanente avec fonctionnement stable, contrôle qualité des données et sans interruptions significatives" },
  { ps:"phase5",oi:2,slug:"p5q2",type:"scale",w:"1.50",
    es:"¿Qué nivel de estructura tiene la reportería de calidad postal?",
    en:"What level of structure do postal quality reports have?",
    fr:"Quel niveau de structure les rapports de qualité postale ont-ils?",
    hes:"1=No se generan reportes / 2=Se generan reportes ad hoc sin estructura ni periodicidad / 3=Reportes periódicos con estructura definida pero elaboración manual / 4=Reportes automatizados mensuales/trimestrales/anuales con comparativas históricas y análisis de tendencias",
    hen:"1=No reports generated / 2=Ad hoc reports generated without structure or periodicity / 3=Periodic reports with defined structure but manual preparation / 4=Automated monthly/quarterly/annual reports with historical comparisons and trend analysis",
    hfr:"1=Pas de rapports générés / 2=Rapports ad hoc sans structure ni périodicité / 3=Rapports périodiques avec structure définie mais préparation manuelle / 4=Rapports automatisés mensuels/trimestriels/annuels avec comparaisons historiques et analyse des tendances" },
  { ps:"phase5",oi:3,slug:"p5q3",type:"scale",w:"1.50",
    es:"¿Se publican los resultados de calidad postal de forma transparente y accesible para los ciudadanos?",
    en:"Are postal quality results published transparently and accessibly for citizens?",
    fr:"Les résultats de qualité postale sont-ils publiés de manière transparente et accessible aux citoyens?",
    hes:"1=No se publican resultados / 2=Se comparten resultados internamente pero no se publican / 3=Se publican resultados de forma parcial o esporádica / 4=Publicación regular en web del regulador o boletín oficial, accesible al ciudadano, con comparativas históricas",
    hen:"1=No results published / 2=Results shared internally but not published / 3=Results published partially or sporadically / 4=Regular publication on regulator website or official bulletin, accessible to citizens, with historical comparisons",
    hfr:"1=Pas de résultats publiés / 2=Résultats partagés en interne mais non publiés / 3=Résultats publiés partiellement ou sporadiquement / 4=Publication régulière sur le site du régulateur ou bulletin officiel, accessible aux citoyens, avec comparaisons historiques" },
  { ps:"phase5",oi:4,slug:"p5q4",type:"scale",w:"2.00",
    es:"¿Existe un sistema de alertas automáticas con protocolo de respuesta ante incumplimientos de SLA?",
    en:"Is there an automatic alert system with a response protocol for SLA non-compliance?",
    fr:"Existe-t-il un système d'alertes automatiques avec un protocole de réponse en cas de non-conformité aux SLA?",
    hes:"1=No hay sistema de alertas / 2=Se detectan incumplimientos manualmente al revisar datos / 3=Hay alertas pero sin protocolo de respuesta definido / 4=Alertas automáticas configuradas por umbral, con protocolo de notificación, plazos de respuesta y escalamiento",
    hen:"1=No alert system / 2=Non-compliance detected manually when reviewing data / 3=Alerts exist but without defined response protocol / 4=Automatic threshold-based alerts with notification protocol, response deadlines and escalation",
    hfr:"1=Pas de système d'alertes / 2=Non-conformité détectée manuellement lors de la révision des données / 3=Alertes existantes sans protocole de réponse défini / 4=Alertes automatiques par seuil avec protocole de notification, délais de réponse et escalade" },
  { ps:"phase5",oi:5,slug:"p5q5",type:"barrier",w:"0.00",
    es:"¿Cuál es el principal obstáculo para sostener la medición continua?",
    en:"What is the main obstacle to sustaining continuous measurement?",
    fr:"Quel est le principal obstacle au maintien de la mesure continue?",
    hes:"Seleccione el obstáculo más relevante.",hen:"Select the most relevant obstacle.",hfr:"Sélectionnez l'obstacle le plus pertinent.",
    options:[
      {value:"no_recurring_funding",labelEs:"Falta de financiamiento para la operación recurrente",labelEn:"Lack of funding for recurring operation",labelFr:"Manque de financement pour l'opération récurrente"},
      {value:"no_dedicated_staff",labelEs:"Falta de personal dedicado a la operación del sistema",labelEn:"Lack of staff dedicated to system operation",labelFr:"Manque de personnel dédié à l'opération du système"},
      {value:"equipment_deterioration",labelEs:"El equipamiento se deteriora y no hay plan de mantenimiento",labelEn:"Equipment deteriorates and there is no maintenance plan",labelFr:"L'équipement se détériore sans plan de maintenance"},
      {value:"panel_maintenance",labelEs:"Dificultad para mantener el panel de panelistas activo",labelEn:"Difficulty maintaining the active panelist panel",labelFr:"Difficulté à maintenir le panel de panélistes actif"},
      {value:"no_sops",labelEs:"Falta de procedimientos operativos estandarizados",labelEn:"Lack of standardized operating procedures",labelFr:"Manque de procédures opérationnelles standardisées"},
      {value:"already_continuous",labelEs:"La medición ya opera de forma continua",labelEn:"Measurement already operates continuously",labelFr:"La mesure fonctionne déjà en continu"},
    ]},

  // ── Phase 6: Improvement Plans ────────────────────────────────────────────
  { ps:"phase6",oi:1,slug:"p6q1",type:"scale",w:"2.00",
    es:"¿Se han realizado análisis de causa raíz para identificar las causas operativas específicas de los retrasos?",
    en:"Have root cause analyses been conducted to identify the specific operational causes of delays?",
    fr:"Des analyses des causes profondes ont-elles été réalisées pour identifier les causes opérationnelles spécifiques des retards?",
    hes:"1=No se ha analizado nunca las causas / 2=Se conocen las causas de forma intuitiva pero sin análisis formal / 3=Se ha realizado algún análisis puntual pero sin metodología estructurada / 4=Análisis de causa raíz formal, con visitas de campo, datos de medición y priorización de problemas",
    hen:"1=Causes never analysed / 2=Causes known intuitively but without formal analysis / 3=Some spot analysis conducted but without structured methodology / 4=Formal root cause analysis with field visits, measurement data and problem prioritisation",
    hfr:"1=Causes jamais analysées / 2=Causes connues intuitivement sans analyse formelle / 3=Quelques analyses ponctuelles sans méthodologie structurée / 4=Analyse formelle des causes profondes avec visites de terrain, données de mesure et priorisation des problèmes" },
  { ps:"phase6",oi:2,slug:"p6q2",type:"scale",w:"2.00",
    es:"¿Existen planes de mejora formales con acciones, responsables, plazos e indicadores de éxito?",
    en:"Are there formal improvement plans with actions, responsible parties, deadlines and success indicators?",
    fr:"Existe-t-il des plans d'amélioration formels avec des actions, des responsables, des délais et des indicateurs de succès?",
    hes:"1=No existen planes de mejora / 2=Se han hecho recomendaciones generales pero sin plan estructurado / 3=Hay planes con acciones definidas pero sin seguimiento ni indicadores / 4=Planes formales con acciones, responsables, plazos, indicadores de éxito y revisiones periódicas de avance",
    hen:"1=No improvement plans exist / 2=General recommendations made but no structured plan / 3=Plans with defined actions but without monitoring or indicators / 4=Formal plans with actions, responsible parties, deadlines, success indicators and periodic progress reviews",
    hfr:"1=Pas de plans d'amélioration / 2=Recommandations générales sans plan structuré / 3=Plans avec actions définies sans suivi ni indicateurs / 4=Plans formels avec actions, responsables, délais, indicateurs de succès et révisions périodiques de l'avancement" },
  { ps:"phase6",oi:3,slug:"p6q3",type:"scale",w:"1.50",
    es:"¿Qué capacidad tiene el regulador para imponer acciones correctivas y sancionar incumplimientos?",
    en:"What capacity does the regulator have to impose corrective actions and sanction non-compliance?",
    fr:"Quelle capacité le régulateur a-t-il pour imposer des actions correctives et sanctionner les manquements?",
    hes:"1=Solo puede recomendar sin consecuencias / 2=Puede emitir recomendaciones formales pero sin poder sancionador / 3=Tiene poder sancionador pero no lo ha ejercido nunca o rara vez / 4=Régimen sancionador activo, vinculado a SLAs, con procedimiento establecido y sanciones aplicadas",
    hen:"1=Can only recommend without consequences / 2=Can issue formal recommendations but without sanctioning power / 3=Has sanctioning power but has never or rarely exercised it / 4=Active sanctioning regime, linked to SLAs, with established procedure and applied sanctions",
    hfr:"1=Peut seulement recommander sans conséquences / 2=Peut émettre des recommandations formelles sans pouvoir de sanction / 3=A un pouvoir de sanction mais ne l'a jamais ou rarement exercé / 4=Régime de sanction actif, lié aux SLA, avec procédure établie et sanctions appliquées" },
  { ps:"phase6",oi:4,slug:"p6q4",type:"scale",w:"1.50",
    es:"¿Se verifica con datos de medición si las acciones de mejora implementadas producen el efecto esperado?",
    en:"Is measurement data used to verify whether implemented improvement actions produce the expected effect?",
    fr:"Les données de mesure sont-elles utilisées pour vérifier si les actions d'amélioration mises en œuvre produisent l'effet attendu?",
    hes:"1=No se verifica el impacto de las mejoras / 2=Se percibe si hay mejora pero sin datos comparativos / 3=Se comparan datos antes/después pero sin metodología rigurosa / 4=Verificación formal con comparación estadística antes/después, documentación de resultados y lecciones aprendidas",
    hen:"1=Impact of improvements not verified / 2=Improvement perceived but without comparative data / 3=Before/after data compared but without rigorous methodology / 4=Formal verification with statistical before/after comparison, results documentation and lessons learned",
    hfr:"1=Impact des améliorations non vérifié / 2=Amélioration perçue sans données comparatives / 3=Données avant/après comparées sans méthodologie rigoureuse / 4=Vérification formelle avec comparaison statistique avant/après, documentation des résultats et leçons apprises" },
  { ps:"phase6",oi:5,slug:"p6q5",type:"barrier",w:"0.00",
    es:"¿Cuál es el principal obstáculo para implementar planes de mejora?",
    en:"What is the main obstacle to implementing improvement plans?",
    fr:"Quel est le principal obstacle à la mise en œuvre des plans d'amélioration?",
    hes:"Seleccione el obstáculo más relevante.",hen:"Select the most relevant obstacle.",hfr:"Sélectionnez l'obstacle le plus pertinent.",
    options:[
      {value:"no_data",labelEs:"No hay datos suficientes para diagnosticar las causas",labelEn:"Insufficient data to diagnose causes",labelFr:"Données insuffisantes pour diagnostiquer les causes"},
      {value:"operator_no_cooperate",labelEs:"El operador no colabora en los planes de mejora",labelEn:"Operator does not cooperate in improvement plans",labelFr:"L'opérateur ne coopère pas aux plans d'amélioration"},
      {value:"no_consultants",labelEs:"Falta de consultores con experiencia en operaciones postales",labelEn:"Lack of consultants with postal operations experience",labelFr:"Manque de consultants avec expérience en opérations postales"},
      {value:"no_regulatory_capacity",labelEs:"No hay capacidad regulatoria para imponer acciones correctivas",labelEn:"No regulatory capacity to impose corrective actions",labelFr:"Pas de capacité réglementaire pour imposer des actions correctives"},
      {value:"staff_turnover",labelEs:"Falta de seguimiento por rotación de personal o cambio de prioridades",labelEn:"Lack of follow-up due to staff turnover or priority changes",labelFr:"Manque de suivi dû à la rotation du personnel ou aux changements de priorités"},
      {value:"already_working",labelEs:"Los planes de mejora ya funcionan",labelEn:"Improvement plans are already working",labelFr:"Les plans d'amélioration fonctionnent déjà"},
    ]},

  // ── Phase 7: Maturity & Continuous Improvement ────────────────────────────
  { ps:"phase7",oi:1,slug:"p7q1",type:"scale",w:"1.50",
    es:"¿Los SLAs se revisan periódicamente con base en datos acumulados y consulta a stakeholders?",
    en:"Are SLAs reviewed periodically based on accumulated data and stakeholder consultation?",
    fr:"Les SLA sont-ils révisés périodiquement sur la base des données accumulées et de la consultation des parties prenantes?",
    hes:"1=Los SLAs no se han revisado nunca / 2=Se han ajustado puntualmente pero sin periodicidad / 3=Revisión periódica pero basada en percepción, no en datos / 4=Ciclo formal de revisión con datos acumulados, consulta a stakeholders y ajuste progresivo al alza",
    hen:"1=SLAs never reviewed / 2=Adjusted sporadically without periodicity / 3=Periodic review but based on perception, not data / 4=Formal review cycle with accumulated data, stakeholder consultation and progressive upward adjustment",
    hfr:"1=SLA jamais révisés / 2=Ajustés ponctuellement sans périodicité / 3=Révision périodique basée sur la perception, pas sur les données / 4=Cycle formel de révision avec données accumulées, consultation des parties prenantes et ajustement progressif à la hausse" },
  { ps:"phase7",oi:2,slug:"p7q2",type:"scale",w:"1.50",
    es:"¿El sistema de medición cubre servicios más allá del correo básico (paquetería, e-commerce, servicios express)?",
    en:"Does the measurement system cover services beyond basic mail (parcels, e-commerce, express services)?",
    fr:"Le système de mesure couvre-t-il des services au-delà du courrier de base (colis, e-commerce, services express)?",
    hes:"1=Solo correo básico / 2=Se ha identificado la necesidad de ampliar pero no se ha hecho / 3=Se miden algunos servicios adicionales pero sin la misma profundidad / 4=Cobertura integral de todos los servicios relevantes del mercado postal con metodología adaptada",
    hen:"1=Basic mail only / 2=Need to expand identified but not yet done / 3=Some additional services measured but without the same depth / 4=Comprehensive coverage of all relevant postal market services with adapted methodology",
    hfr:"1=Courrier de base seulement / 2=Besoin d'expansion identifié mais non encore réalisé / 3=Certains services supplémentaires mesurés sans la même profondeur / 4=Couverture complète de tous les services postaux pertinents avec méthodologie adaptée" },
  { ps:"phase7",oi:3,slug:"p7q3",type:"scale",w:"2.00",
    es:"¿El país participa en programas internacionales de medición de calidad postal?",
    en:"Does the country participate in international postal quality measurement programmes?",
    fr:"Le pays participe-t-il à des programmes internationaux de mesure de la qualité postale?",
    hes:"1=No participa en ningún programa / 2=Conoce los programas pero no participa / 3=Participa de forma puntual o con datos limitados / 4=Participación activa y continua en UPU GMS u otros programas con intercambio de datos y metodología compatible",
    hen:"1=Does not participate in any programme / 2=Aware of programmes but does not participate / 3=Participates sporadically or with limited data / 4=Active and continuous participation in UPU GMS or other programmes with data exchange and compatible methodology",
    hfr:"1=Ne participe à aucun programme / 2=Connait les programmes mais n'y participe pas / 3=Participe ponctuellement ou avec des données limitées / 4=Participation active et continue au GMS de l'UPU ou autres programmes avec échange de données et méthodologie compatible" },
  { ps:"phase7",oi:4,slug:"p7q4",type:"scale",w:"1.50",
    es:"¿Se mide la satisfacción del usuario final como complemento a los indicadores objetivos de calidad?",
    en:"Is end-user satisfaction measured as a complement to objective quality indicators?",
    fr:"La satisfaction de l'utilisateur final est-elle mesurée en complément des indicateurs objectifs de qualité?",
    hes:"1=No se mide satisfacción / 2=Se reciben quejas pero no se analizan sistemáticamente / 3=Encuestas puntuales sin periodicidad ni integración con datos de calidad / 4=Medición periódica de satisfacción integrada con indicadores objetivos y utilizada en la revisión de SLAs",
    hen:"1=Satisfaction not measured / 2=Complaints received but not systematically analysed / 3=Spot surveys without periodicity or integration with quality data / 4=Periodic satisfaction measurement integrated with objective indicators and used in SLA review",
    hfr:"1=Satisfaction non mesurée / 2=Plaintes reçues mais non analysées systématiquement / 3=Enquêtes ponctuelles sans périodicité ni intégration avec données de qualité / 4=Mesure périodique de satisfaction intégrée aux indicateurs objectifs et utilisée dans la révision des SLA" },
  { ps:"phase7",oi:5,slug:"p7q5",type:"barrier",w:"0.00",
    es:"¿Cuál es el principal obstáculo para alcanzar la madurez continua?",
    en:"What is the main obstacle to achieving continuous maturity?",
    fr:"Quel est le principal obstacle à l'atteinte de la maturité continue?",
    hes:"Seleccione el obstáculo más relevante.",hen:"Select the most relevant obstacle.",hfr:"Sélectionnez l'obstacle le plus pertinent.",
    options:[
      {value:"slas_not_questioned",labelEs:"Los SLAs actuales no se cuestionan",labelEn:"Current SLAs are not questioned",labelFr:"Les SLA actuels ne sont pas remis en question"},
      {value:"no_demand_new_services",labelEs:"No hay demanda para medir nuevos servicios",labelEn:"No demand to measure new services",labelFr:"Pas de demande pour mesurer de nouveaux services"},
      {value:"no_resources_international",labelEs:"Falta de recursos para participar en programas internacionales",labelEn:"Lack of resources to participate in international programmes",labelFr:"Manque de ressources pour participer aux programmes internationaux"},
      {value:"incompatible_methodology",labelEs:"La metodología no es compatible con estándares internacionales",labelEn:"Methodology not compatible with international standards",labelFr:"Méthodologie non compatible avec les normes internationales"},
      {value:"no_peer_network",labelEs:"Falta de interlocución con otros reguladores",labelEn:"Lack of dialogue with other regulators",labelFr:"Manque de dialogue avec d'autres régulateurs"},
      {value:"already_mature",labelEs:"El sistema ya está en fase de madurez",labelEn:"The system is already in a maturity phase",labelFr:"Le système est déjà en phase de maturité"},
    ]},
];

const PROVIDERS_DATA = [
  { nameEs:"Soluciones de Panelistas Postales",nameEn:"Postal Panelist Solutions",
    descriptionEs:"Diseño e implementación de redes de panelistas para medición E2E de calidad postal según estándares UPU S58/S59 y EN 13850.",
    descriptionEn:"Design and implementation of panelist networks for E2E postal quality measurement per UPU S58/S59 and EN 13850 standards.",
    category:"measurement" as const,relevantPhases:JSON.stringify(["phase1","phase3"]),website:"https://example.com",contactEmail:"contact@example.com",featured:true,active:true,caseStudies:JSON.stringify([]) },
  { nameEs:"Plataformas de Datos Regulatorios",nameEn:"Regulatory Data Platforms",
    descriptionEs:"Plataformas SaaS para centralizar, analizar y reportar datos de calidad postal con dashboards interactivos y alertas automáticas.",
    descriptionEn:"SaaS platforms to centralize, analyze and report postal quality data with interactive dashboards and automatic alerts.",
    category:"platform" as const,relevantPhases:JSON.stringify(["phase1","phase5"]),website:"https://example.com",contactEmail:"contact@example.com",featured:true,active:true,caseStudies:JSON.stringify([]) },
  { nameEs:"Sistemas RFID para Redes Postales",nameEn:"RFID Systems for Postal Networks",
    descriptionEs:"Equipamiento RFID y sistemas de captura para diagnóstico granular de tiempos por nodo y tramo en redes postales.",
    descriptionEn:"RFID equipment and capture systems for granular diagnosis of times per node and segment in postal networks.",
    category:"rfid" as const,relevantPhases:JSON.stringify(["phase4"]),website:"https://example.com",contactEmail:"contact@example.com",featured:false,active:true,caseStudies:JSON.stringify([]) },
  { nameEs:"Consultoría Regulatoria Postal",nameEn:"Postal Regulatory Consulting",
    descriptionEs:"Servicios de consultoría especializada en diseño de marcos regulatorios, SLAs, análisis de causa raíz y planes de mejora postal.",
    descriptionEn:"Specialized consulting services in regulatory framework design, SLAs, root cause analysis and postal improvement plans.",
    category:"consulting" as const,relevantPhases:JSON.stringify(["phase2","phase3","phase6","phase7"]),website:"https://example.com",contactEmail:"contact@example.com",featured:true,active:true,caseStudies:JSON.stringify([]) },
  { nameEs:"Formación y Capacitación Postal",nameEn:"Postal Training & Capacity Building",
    descriptionEs:"Programas de formación para reguladores postales en medición de calidad, análisis de datos y mejora continua.",
    descriptionEn:"Training programs for postal regulators in quality measurement, data analysis and continuous improvement.",
    category:"training" as const,relevantPhases:JSON.stringify(["phase1","phase5","phase6"]),website:"https://example.com",contactEmail:"contact@example.com",featured:false,active:true,caseStudies:JSON.stringify([]) },
];

async function seed() {
  const connection = await mysql.createConnection(process.env.DATABASE_URL!);
  const db = drizzle(connection);

  console.log("Clearing existing questions and phases...");
  await db.delete(questions);
  await db.delete(phases);

  console.log("Seeding phases...");
  for (const phase of PHASES_DATA) {
    await db.insert(phases).values(phase);
  }

  const phaseRows = await db.select().from(phases);
  const phaseMap = new Map(phaseRows.map((p) => [p.slug, p.id]));

  console.log("Seeding questions...");
  for (const q of Q) {
    const phaseId = phaseMap.get(q.ps);
    if (!phaseId) throw new Error(`Phase not found: ${q.ps}`);
    await db.insert(questions).values({
      phaseId,
      orderIndex: q.oi,
      slug: q.slug,
      textEs: q.es,
      textEn: q.en,
      textFr: q.fr,
      helpEs: q.hes,
      helpEn: q.hen,
      helpFr: q.hfr,
      questionType: q.type,
      weight: q.w,
      options: "options" in q && q.options ? JSON.stringify(q.options) : null,
    });
  }

  console.log("Seeding market providers...");
  for (const p of PROVIDERS_DATA) {
    await db.insert(marketProviders).values(p).onDuplicateKeyUpdate({ set: { nameEs: p.nameEs } });
  }

  console.log(`✅ Seed complete! ${PHASES_DATA.length} phases, ${Q.length} questions`);
  await connection.end();
}

seed().catch((e) => { console.error(e); process.exit(1); });
